### ISSUE TITLE
Error when run ochrona command using a .ochrona.yml without defining a policies key.

### ISSUE THREAD

**Issue by igor-rodrigues1** [ochronasec/ochrona-cli#61]
**Describe the bug**
I need to execute the ochrona validation using a .ochrona.yml with only ignore key, but if I don't define a policies configuration with some parameter or even though an  empty police I receive this error.

```Traceback (most recent call last):
  File ".venv/bin/ochrona", line 8, in <module>
    sys.exit(run())
  File ".venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File ".venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File ".venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File ".venv/lib/python3.8/site-packages/ochrona/cli/cli.py", line 107, in run
    config = OchronaConfig(
  File ".venv/lib/python3.8/site-packages/ochrona/config/config.py", line 46, in __init__
    valid = self._validate()
  File ".venv/lib/python3.8/site-packages/ochrona/config/config.py", line 175, in _validate
    if len(self._policies) > 0:
TypeError: object of type 'NoneType' has no len()
```

But, If I use the ```.ochrona.yml``` with the follow content the ochrona validation work normally:
```
ignore:
  - requests
policies: []
```
But, adding empty keys for a configuration that I won't use doesn't seem to be necessary.

Apparently the error can occur due to this [line](https://github.com/ochronasec/ochrona-cli/blob/95d9c3cdbfa901967a497913e88a2ea2a4c766da/ochrona/config/config.py#L150) because if the ```polices``` key does not exist in .ochrona.yml a ```None``` value will be returned to ```self._policies```.

**To Reproduce**
- Create ```.ochrona.yml``` file.
- Add the follow content in ```.ochrona.yml``` file:
```
  ignore: 
    - requests
```

- Run ochrona command:

```shell
ochrona
```

**Expected behavior**
Run the vulnerability validation using only ```ignore``` key inside ```.ochrona.yml```.

**Background (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Python Version: 3.8.10
 - Ochrona Version: 2.0.0
 - Ochrona Arguments: ```None``` or ```-r requirements.txt --report_type FULL```

**Comment by beatsbears** [comment]
Thanks for reporting the detailed issue, @igor-rodrigues1 . I'll get a fix up for this as soon as possible
