### ISSUE TITLE
exclude_dir is ignored when specified as list in yaml config

### ISSUE THREAD

**Issue by kupcimat** [ochronasec/ochrona-cli#64]
**Describe the bug**
`exclude_dir` configuration property is ignored when specified as a list in the `.ochrona.yml`. It works as expected if specified as a comma separated string, e.g.:
```yaml
exclude_dir: exclude_dir1,exclude_dir2
```

**To Reproduce**
1. Create the following `.ochrona.yml` configuration:
```yaml
---
dir: root_dir
exclude_dir:
  - exclude_dir1
  - exclude_dir2
debug: true
```
2. Run `ochrona`

**Expected behavior**
`exclude_dir1` and `exclude_dir2` should be excluded from the recursive search.

**Background:**
 - OS: OSX 12.5
 - Python Version: python 3.8.7
 - Ochrona Version: 2.0.1
 - Ochrona Arguments: no arguments, using `.ochrona.yml` instead
 - Debug output: running with debug flag just lists all dependency files including those in `exclude_dir`

**Additional context**
I thought the problem was with the yaml parsing, but it looks like `ochrona.config.OchronaConfig` works as expected and correctly returns a list for `exclude_dir`. Also `ignore` configuration property works as list without any problems. So it is probably something else, but I didn't do a more detailed investigation. Thank you!

**Comment by beatsbears** [comment]
Hi @kupcimat, thanks for reporting this. I'll add a fix as soon as I can.
